language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
dist: xenial
install:
    - python setup.py install
    - pip install pylint pytest coverage
script:
    - coverage run --source linode_api4 -m pytest
    - coverage report
    - pylint linode_api4
